### PR TITLE
PR (#265) revised

### PR DESCRIPTION
**Pull request by Mistadouf**
## Description
As per requested, changed my PR to the new files format.

## Motivation and Context
Updated per https://github.com/vatsimnetwork/simaware-tracon-project/pull/265

## Is this a breaking change?

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My change or addition follow the formatting standard of the project.
- [x] I am on the list of approved contributors.

### CODE REVIEW

**Comment by Mistadouf** [comment]
@kmoberg I've updated per your request.

**Review by kmoberg — CHANGES_REQUESTED** [review]
We've been discussing with the developer of Simaware and unfortunately our guess is that a list of prefixes will not work - it will not light up at all. The solution is to add a new sector (a separate CPTL airport folder), create a new sector with the ID and prefix 'CPTL' that includes the polygons for both CYOW and CYQB.  CZEG already did this for YYC and YEG!

**Comment by kmoberg** [comment]
Also, huge thanks for updating with the format! :)

**Comment by Mistadouf** [comment]
as requested, added CPTL folder with both polygons in 1 file

**Review by kmoberg — APPROVED** [review]
Fantastic! Let's give this a try!

**Pull request merged**
