### PR TITLE
Added CZUL TCAs

### PR DESCRIPTION
**Pull request by Mistadouf**
## Description
Added CYUL, CYQB, CYOW and CYBG TCAs

## Motivation and Context
Added new TCAs for the Montreal FIR that were not already in the files.

## How to prove the effect of this PR?
CYUL:
image
CYQB:
image
CYOW:
image
CYBG:
image
Global change:
image

## Is this a breaking change?
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [X] My change or addition follows the formatting standard of the project.
- [x] I am on the list of approved contributors.

### CODE REVIEW

**Comment by Mistadouf** [comment]
I am not yet on the list of approved contributors. I sent an email but haven't received a reply yet. I am the FE and Chief for the Montreal FIR. https://www.czul.ca/en/fir_staff/

**Comment by Mistadouf** [comment]
Also, we have a control position (CPTL_APP) that covers both the CYOW and CYQB TCAs, Can I just add multiple prefixes for this to work? I.e. "prefix":["CYOW","CPTL"]

**Comment by Mistadouf** [comment]
> I am not yet on the list of approved contributors. I sent an email but haven't received a reply yet. I am the FE and Chief for the Montreal FIR. https://www.czul.ca/en/fir_staff/

I now have received a reply from Karl.

**Comment by kmoberg** [comment]
> Also, we have a control position (CPTL_APP) that covers both the CYOW and CYQB TCAs, Can I just add multiple prefixes for this to work? I.e. "prefix":["CYOW","CPTL"]

As of now, I don't think that will work. @maiuswong could clarify here.

**Review by kmoberg — APPROVED** [review]

**Pull request merged**
