### PR TITLE
Add ULLI, ULLL Boundaries

### PR DESCRIPTION
**Pull request by sanek1000804**
By Alexander Pervov

### CODE REVIEW

**Comment by sanek1000804** [comment]
image

**Review by dirtyformal — APPROVED** [review]
Sectors look good to me! Thanks for your contribution!

**Comment by sanek1000804** [comment]
> Sectors look good to me! Thanks for your contribution!

Thank you for fast response, glad you liked it)

**Review by kmoberg — APPROVED** [review]
Looks great! Thank you! 🤩

**Pull request merged**
