### PR TITLE
Build Script

### PR DESCRIPTION
**Pull request by justinshannon**
This PR separates the combined boundary file into separate JSON files for each boundary. This change allows for better change management and makes it easier for users to contribute new boundaries or update existing ones.

Utilizing GitHub Actions, the compiler script traverses all the JSON files in the `Boundaries` folder and combines them into a single GeoJSON file. If the commit is version tagged (e.g. v1.0.0), the workflow will create a new Release and attach the compiled boundary GeoJSON file.

The latest Release file can be easily obtained using the GitHub latest release API: https://api.github.com/repos/vatsim/simaware-tracon-project/releases/latest. You can see an example of this on my fork [here](https://api.github.com/repos/justinshannon/simaware-tracon-project/releases/latest); the `browser_download_url` property contains the direct link to the compiled GeoJSON file.

### CODE REVIEW

**Comment by kmoberg** [comment]
Wow, this is fantastisk, and makes life a heck of a lot easier for everyone! @justinshannon Has this been coordinated with @maiuswong to pull the releases from the repo?

**Comment by maiuswong** [comment]
looks good. thanks justin!

**Comment by kmoberg** [comment]
@justinshannon Seems like we're good to go! 🤩 Could you update with the latest changes, and we'll hold off on pushing further updates until that is done?

**Comment by justinshannon** [comment]
The boundaries have been updated with the latest changes (excluding the outstanding pull requests).

**Review by kmoberg — APPROVED** [review]

**Pull request merged**
