### PR TITLE
Add UNSS Boundary, fix USCC and USTR

### PR DESCRIPTION
**Pull request by sanek1000804**
## Description

This change will add Boundary for UNSS_R_APP ATC position.

## Motivation and Context

This change will add real Boundary for Karavay Krug

## How to prove the effect of this PR?

(http://www.caiga.ru/common/AirInter/validaip/html/rus.htm)
image
image

## Checklist

- [x] My change or addition follow the formatting standard of the project.
- [x] I am on the list of approved contributors.

### CODE REVIEW

**Review by dirtyformal — CHANGES_REQUESTED** [review]
Hey there, thanks for the contribution.

The boundary between UNSS and USRR don't quite match up - can you please fix that before we merge this? Thanks!

image

**Comment by sanek1000804** [comment]
> Hey there, thanks for the contribution.
> 
> The boundary between UNSS and USRR don't quite match up - can you please fix that before we merge this? Thanks!
> 
> image

I take coordinates from real documents. And in them, unfortunately, for some reason, the border CTA UNSS don't match up with CTA USRR. I will using part of the UNSS CTR coordinates, which also borders with USRR, to make the border look better.

**Comment by sanek1000804** [comment]
There also was a problem with real USRR boundary, which hadn't match with FIR's boundary. I fixed UNSS and USRR boundaries. Now they matches with each others and FIR's boundary perfectly.

**Comment by sanek1000804** [comment]
image

**Comment by sanek1000804** [comment]
Also have fixed border between USSS and USCC

**Review by dirtyformal — APPROVED** [review]
Happy with it now! Thank you!

**Comment by sanek1000804** [comment]
> Happy with it now! Thank you!

Please, request review from kmoberg. It seems, it have deleted somehow when I requested re-review from you.

**Comment by sanek1000804** [comment]
And also fix USTR border with FIR. Sorry for such a fragmented pull request)

**Comment by Soofushka** [comment]
@kmoberg

**Review by dirtyformal — APPROVED** [review]
Happy with the changes to USTR as well. No worries about the PR - don't stress. :)

**Review by kmoberg — APPROVED** [review]

**Pull request merged**
