### PR TITLE
T75 Main Update to include SPI and PIA areas

### PR DESCRIPTION
**Pull request by abusivemilk**
I would possibly wait on this merge until KC has time to update their SOPs, etc.

### CODE REVIEW

**Review by dirtyformal — APPROVED** [review]
Changes look good to me.

Is there an estimated release date for their SOPs? We're more than happy to hold off on merging these - just come back here and kick us when it's time!

**Comment by kmoberg** [comment]
@abusivemilk Status?

**Comment by abusivemilk** [comment]
I'll check tomorrow @kmoberg

**Comment by abusivemilk** [comment]
Good to merge

**Pull request merged**
