### PR TITLE
Fixed Radars for Rostov FIR

### PR DESCRIPTION
**Pull request by Atsamazz**
Fixed R_APP ( Radars ) for Rostov FIR. Deleted suffix and added prefix ( ICAO_R )

### CODE REVIEW

**Review by kmoberg — APPROVED** [review]
Very nice!

**Comment by kmoberg** [comment]
@Atsamazz There is a merge conflict with main here, can you make sure to resolve it so I can merge it?

**Comment by Atsamazz** [comment]
> @Atsamazz There is a merge conflict with main here, can you make sure to resolve it so I can merge it?

I will check what is the conflict, but it is strange. It seems everything is ok, but i will check when I will be at home)

**Comment by Atsamazz** [comment]
@kmoberg Check it please

**Review by kmoberg — APPROVED** [review]

**Comment by kmoberg** [comment]
Excellent! Thanks!

**Pull request merged**
