### PR TITLE
Actually Eglin Approach this time

### PR DESCRIPTION
**Pull request by abusivemilk**

### CODE REVIEW

**Review by dirtyformal — CHANGES_REQUESTED** [review]
Thanks for the resubmit!

There's some areas of the polygon where it doesn't quite mate up with the adjoining sectors - particularly to the north with OZR, and to the west with an overlap of PNS. This looks to be the case with Jacksonville ARTCC's TRACON map, too.

This is sub-optimal, as if these positions were online, it would look rather untidy. Could you please fix this, and then I'll be happy to approve.

Cheers!

VPS

**Comment by abusivemilk** [comment]
Updated


Evan Bradley
[phone] 512-655-3633
[email] ***@***.***

**Review by dirtyformal — APPROVED** [review]

**Comment by dirtyformal** [comment]
Thanks! I just quickly had to fix the `"coordinates"` definition, as it prevented parsing, but looks good now. Thanks for your contribution!

**Review by kmoberg — APPROVED** [review]
Second time's the charm! 👍

**Pull request merged**
