### PR TITLE
Define U.A.E FIR Approach Areas

### PR DESCRIPTION
**Pull request by luke11brown**
## Description
Adds definitions for the following approach/departure positions:
- Abu Dhabi (OMAA)
- Dubai (OMDB)
- Fujairah (OMFJ)
- Ras Al Khaimah (OMRK)
- Al Ain (OMAL)

## Motivation and Context
No previous definitions

## How to prove the effect of this PR?
OMAA
image

OMDB
image

OMFJ
image

OMRK
image

OMAL
image

All areas compound image
image

## Additional info
Review from @Dedpewlcontrol or @ranbi2delta

## Is this a breaking change?
No

## Checklist

- [x] My change or addition follow the formatting standard of the project.
- [ ] I am on the list of approved contributors.

### CODE REVIEW

**Comment by dirtyformal** [comment]
Hi there @luke11brown, can you please follow the approval guidelines for contributors as stated in the repository readme? After that, I will review your PR.

**Comment by luke11brown** [comment]
Hi, I'm not vACC staff, hence why I noted review will be from vACC staff @Dedpewlcontrol or @Ranbi2delta

**Comment by dirtyformal** [comment]
> Hi, I'm not vACC staff, hence why I noted review will be from vACC staff @DedpewlControl or @Ranbi2Delta

Cool - get them to email me please.

**Comment by DedpewlControl** [comment]
Hello! Email sent from my side!

**Comment by Ranbi2Delta** [comment]
Hi,

Approved from my end.

Suprojit

**Comment by luke11brown** [comment]
Noted around Argoob that the centre of the arc was used instead of the circumference, now fixed.

image

**Comment by dirtyformal** [comment]
Merged!

**Pull request merged**
