### PR TITLE
Add Caucasus TMAs

### PR DESCRIPTION
**Pull request by Soofushka**
Added Caucasus TMAs boundaries

## Description
Added Azerbaijan, Armenian and Georgian TMAs boundaries

## Motivation and Context
Added boundaries to appear on SimAware when APP in Azerbaija, Armenia and Georgia

## How to prove the effect of this PR?
image

## Is this a breaking change?

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My change or addition follow the formatting standard of the project.
- [x] I am on the list of approved contributors.

### CODE REVIEW

**Comment by kmoberg** [comment]
We have some questions around the level of detail in these borders. Are the detail in the TMA border here what it is in real-world? Is there a sector file that you can show us that depicts the same borders? Or concern is two fold: 

first, such a level of details around some of the borders can increase the complexity for pilots and in reality make it harder for a pilot to understand, compared to just a simple straight line across. 

Our second concern is the complexity level for maintaining this border. Being this detailed, makes it a **huge** workload for the TMA on the other side of the border to maintain and requires them as well to conform to this level of detail when it might not be needed. It also makes it much more complicated to change in the future.

**Comment by Soofushka** [comment]
You can found sector-files on GNG, where you can see similar borders for each TMA. Similar borders can be found in AIP

**Comment by kmoberg** [comment]
> You can found sector-files on GNG, where you can see similar borders for each TMA. Similar borders can be found in AIP

Sorry, but can you please provide screenshots, we don't have the time to start digging through each countries AIP for borders like these.

The big question about complexity still stand: is it worth it in the long run to maintain such a complex and detailed border for a virtual environment?

**Comment by Soofushka** [comment]
image
image

**Comment by Soofushka** [comment]
> > You can found sector-files on GNG, where you can see similar borders for each TMA. Similar borders can be found in AIP
> 
> Sorry, but can you please provide screenshots, we don't have the time to start digging through each countries AIP for borders like these.
> 
> The big question about complexity still stand: is it worth it in the long run to maintain such a complex and detailed border for a virtual environment?

I think that mb Fuzulli,Ganja and Nakhchivan TMAs can be deleted as they really heavy but others should be implemented, as Tbilisi and Yerevan main airports of Georgia and Armenia + Kutaisi/Batumi as they quite small => they are so easy to maintain.
Do you agree with me?

**Pull request closed without merging**
