### PR TITLE
Update USHB

### PR DESCRIPTION
**Pull request by sanek1000804**
## Description
Updating of USHB boundary for USHB_INF_APP use

## How to prove the effect of this PR?
image
image

## Is this a breaking change?

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My change or addition follow the formatting standard of the project.
- [x] I am on the list of approved contributors.

### CODE REVIEW

**Review by dirtyformal — CHANGES_REQUESTED** [review]
Hi there, I see this PR is to change the sector's name from 'Approach' to 'Information'.

What is this sector's purpose? Do they provide an Approach service (procedural or radar), or do they provide an information relay service?

If it is the latter, then this entry should be removed from the dataset.

**Comment by dirtyformal** [comment]
Hi @sanek1000804, could you please answer my question above?

**Comment by sanek1000804** [comment]
> Hi @sanek1000804, could you please answer my question above?
Hello. Sorry for not answering for a long time.
There was an approach, but it was removed some time ago. So only information service remained. We decided to make its boundary because we use it at events sometimes and it covers big area with few airfields.
Answering your question, it is second option. Berezovo Information provides only information service, not approach

**Comment by dirtyformal** [comment]
No worries at all - thanks for your response! 

In that case, it's better off if this position is removed from the dataset. Are you able to amend your PR to achieve this?

**Comment by sanek1000804** [comment]
> No worries at all - thanks for your response!
> 
> In that case, it's better off if this position is removed from the dataset. Are you able to amend your PR to achieve this?

Sure. Done

**Comment by dirtyformal** [comment]
Thanks for that! Merging now :)

**Pull request merged**
