### PR TITLE
Fix GEG_C_APP

### PR DESCRIPTION
**Pull request by MatthewArmstrong1**
Fixed the malformed file which caused GEG_C_APP to break on Simaware

## Description
Not much really too add here

## Motivation and Context
Fixes to pull request #321

## How to prove the effect of this PR?
When a GEG_C_APP controller signs on, the position should look like this:
geojson proof

## Is this a breaking change?
I don't believe so

## Checklist
- [ x] My change or addition follow the formatting standard of the project.
- [x ] I am on the list of approved contributors.

### CODE REVIEW

**Review by dirtyformal — CHANGES_REQUESTED** [review]
Hi there, thanks for your submission.

The sector you've submitted doesn't quite line up with the MWH neighbouring sector, and I've highlighted the concerned areas in red.

Can you please double check your data, and make sure this is correct? It would be unusual for a sector not to match up properly. I tried to locate some supporting documentation for the sector as you have it, but couldn't locate any.

Many thanks!

image

**Comment by dirtyformal** [comment]
@MatthewArmstrong1 - Can you please action our requests on this PR? If this goes stale we may close this PR.

**Comment by MatthewArmstrong1** [comment]
Hi,

yup I’ve been pretty busy recently with personal stuff. I’ll work on getting that documentation and rebuilding the geojson give me a few days

Thanks for the reminder

**Comment by kmoberg** [comment]
No response. Closing the PR. Feel free to resubmit once you have implemented the fixes.

**Pull request closed without merging**
