### PR TITLE
Add Slovakia TMAs

### PR DESCRIPTION
**Pull request by Soofushka**
Add Slovakia TMAs

## Description
Added Slovakia TMAs

## Motivation and Context
Initial release

## How to prove the effect of this PR?
image

## Additional info
Slovakia AIP: https://aim.lps.sk/web/
Sectorfile: https://files.aero-nav.com/LZBB

## Is this a breaking change?

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My change or addition follow the formatting standard of the project.
- [ ] I am on the list of approved contributors.

### CODE REVIEW

**Review by kmoberg — CHANGES_REQUESTED** [review]
I appreciate the enthusiasm, but do you have approval from vACC Slovakia to make these changes on behalf of them? Feel free to reach out to me via email if that is easier k.moberg@vatsim.net.

**Comment by Soofushka** [comment]
I asked for vACC Slovakia approval, standing by for them) 

> I appreciate the enthusiasm, but do you have approval from vACC Slovakia to make these changes on behalf of them? Feel free to reach out to me via email if that is easier [k.moberg@vatsim.net](mailto:k.moberg@vatsim.net).

**Comment by Soofushka** [comment]
I dont think that they will be against these changes, but anyway

**Comment by Soofushka** [comment]
@kmoberg any emails from Slovakia?

**Comment by Soofushka** [comment]
@kmoberg

**Comment by kmoberg** [comment]
@Soofushka I have not reached out to Slovakia. You'll have to do that and follow the instructions in `README.MD` specifically: [How do I verify my account to submit updates](https://github.com/vatsimnetwork/simaware-tracon-project#how-do-i-verify-my-account-to-submit-updates)

**Comment by Soofushka** [comment]
@kmoberg i cant reach out to Slovakia for about 1 month🤷🏼‍♂️

**Comment by Soofushka** [comment]
@kmoberg 
66AA028E-C17F-49B7-9DBD-41559C782F6D

**Comment by Soofushka** [comment]
@kmoberg

**Comment by Soofushka** [comment]
@kmoberg @dirtyformal LGTM?

**Review by dirtyformal — CHANGES_REQUESTED** [review]
The polygon points look good to me.

Can you confirm whether the position name that you've put for `LZIB_APP` is correct? You've entered it as being "**Stefanik** Approach", whereas the Sector Files define it as being named "Stefanik **Radar**".

Additionally, as you're not a staff member of the Sub-Division, we won't be adding you to the list of approved contributors, as that is intended for people who are designated Facility Engineers for that FIR.

Cheers.

**Comment by Soofushka** [comment]
> The polygon points look good to me.
> 
> Can you confirm whether the position name that you've put for `LZIB_APP` is correct? You've entered it as being "Stefanik _Approach_", whereas the Sector Files define it as being named "Stefanik _Radar_".
> 
> Additionally, as you're not a staff member of the Sub-Division, we won't be adding you to the list of approved contributors, as that is intended for people who are designated Facility Engineers for that FIR. As this data amendment has been approved by the Sub-Division, I'm happy to accept this PR, but going forward they'll need to supply this data.
> 
> Cheers.

Stefanik Radar. Fixed in LZIB.json

**Review by dirtyformal — APPROVED** [review]
Data now looks good to me.

**Comment by Soofushka** [comment]
> Data now looks good to me.

Fine. Btw i dont really understand, why i can’t upload boundaries on SimAware if i have permission from vACC and confirmation that all changes i prepared for their vACC are correct?

**Comment by dirtyformal** [comment]
> Fine. Btw i dont really understand, why i can’t upload boundaries on SimAware if i have permission from vACC and confirmation that all changes i prepared for their vACC are correct?

You might have misinterpreted what I said. 

As the Slovakian vACC have approved these changes, we are happy to accept them. However, their approval was specifically for this amendment. Any changes going forth from this one will have to come from the Slovakian vACC themselves. We do not know if your changes are correct, and do not have time to perform the research to confirm this, as we have other commitments. If the data comes from the designated FE for that vACC, that satisfies that requirement, and saves us from performing a significant amount of work to verify and validate.

**Pull request merged**
